### ISSUE TITLE
MLIR-to-LLVM-IR translation failed because 'btor.input' is unknown

### ISSUE THREAD

**Issue by Po-Chun-Chien** [agurfinkel/btor2mlir#37]
I ran the below commands (following the instructions in [README](https://github.com/agurfinkel/btor2mlir/blob/6feb6ad651f1dfc86f740a0f0e155729e9560a94/README.md))
to translate the Btor2 circuit [recount4.btor2](https://github.com/Boolector/btor2tools/blob/8775f9ad9caed51d3daa30a416b1a94dfec532b0/examples/btorsim/recount4.btor2) to an LLVM-IR program.
A docker image built from commit 6feb6ad6 was used.

1. `build/bin/btor2mlir-translate --import-btor recount4.btor2 > recount4.mlir`
2. `build/bin/btor2mlir-opt  --convert-std-to-llvm --convert-btor-to-llvm recount4.mlir > recount4.mlir.opt`
3. `build/bin/btor2mlir-translate --mlir-to-llvmir recount4.mlir.opt > recount4.ll`

The first 2 steps succeeded, but the 3rd one failed with the error message:

```
recount4.mlir.opt:10:10: error: custom op 'btor.input' is unknown
    %4 = btor.input 0 : !btor.bv<1>
         ^
```

Should I specify any additional command-line arguments to `btor2mlir-translate` or `btor2mlir-opt` to make the translation work?
Or the translation of Btor2's `input` to LLVM-IR is currently not supported?

**Comment by jetafese** [comment]
For this case, it is advised to use the path that translates inputs and non-deterministic assignments `--convert-btornd-to-llvm --convert-btor-to-llvm --convert-std-to-llvm`

After step 2 is completed, you should not see any operations with the `btor.` prefix since that step should produce operations that are only in the llvm dialect.

For the record, the main development happens in the linked repository

**Comment by Po-Chun-Chien** [comment]
Thanks for the clarification!

**Comment by Po-Chun-Chien** [comment]
@jetafese I tried the 2nd command above with the command-line arguments you provided using the latest commit (345625097) in the development [fork](https://github.com/jetafese/btor2mlir).

After running the command, the file `recount4.mlir.btor2` still contains lines like:

```
%10 = builtin.unrealized_conversion_cast %9 : i1 to !btor.bv<1>
```

And the subsequent step failed with

```
recount4.mlir.opt:20:63: error: `!"btor"<"bv<1>">` type created with unregistered dialect. If this is intended, please call allowUnregisteredDialects() on the MLIRContext, or use -allow-unregistered-dialect with the MLIR opt tool used
    %10 = builtin.unrealized_conversion_cast %9 : i1 to !btor.bv<1>
                                                              ^
```

**Comment by jetafese** [comment]
This [script](https://github.com/jetafese/btor2mlir/blob/main/utils/cex/witness/get_cex_seahorn.sh#L34) is a good resource to see what passes are useful for executing the entire pipeline. Feel free to open an issue in the development fork so that our communication is centralized. I'm happy to answer any specific questions that might arise

**Comment by Po-Chun-Chien** [comment]
Thanks again for the pointer!

> Feel free to open an issue in the development fork so that our communication is centralized.

Issue seems to be disabled in the fork.

![Screenshot 2024-06-06 at 16-03-17 jetafese_btor2mlir Bᴛᴏʀ2MLIR A Format and Toolchain for Hardware Verification](https://github.com/agurfinkel/btor2mlir/assets/26144660/c71e6cb8-7a3a-4787-b659-491c58fa87a4)

**Comment by jetafese** [comment]
should be fixed now
